### PR TITLE
Fix `mkl` and `mkl_devel` pinning

### PR DESCRIPTION
**Pull request by ericpre**
Remove `mkl` and `mkl_devel` pinning, now that https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5289 is merged - see https://github.com/conda-forge/numexpr-feedstock/pull/58#issuecomment-1859116174 for background.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [n/a] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [n/a] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ericpre** [comment]
@conda-forge-admin, please rerender

**Comment by ericpre** [comment]
@conda-forge-admin, please rerender

**Comment by ericpre** [comment]
Conda-smithy fails because of https://github.com/conda-forge/conda-smithy/pull/1816.

**Comment by ericpre** [comment]
@conda-forge-admin , please re-render

**Comment by ericpre** [comment]
From the conda-smithy log:
```
INFO:webservices_dispatch_action.rerendering:rerendering
Traceback (most recent call last):
  File "/opt/conda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/conda_smithy/cli.py", line 725, in main
    args.subcommand_func(args)
  File "/opt/conda/lib/python3.10/site-packages/conda_smithy/cli.py", line 585, in __call__
    self._call(args, tmpdir)
  File "/opt/conda/lib/python3.10/site-packages/conda_smithy/cli.py", line 590, in _call
    configure_feedstock.main(
  File "/opt/conda/lib/python3.10/site-packages/conda_smithy/configure_feedstock.py", line 2502, in main
    exclusive_config_file, cf_pinning_ver = get_cached_cfp_file_path(
  File "/opt/conda/lib/python3.10/site-packages/conda_smithy/configure_feedstock.py", line 2326, in get_cached_cfp_file_path
    get_cfp_file_path(smithy_cache)
  File "/opt/conda/lib/python3.10/site-packages/conda_smithy/configure_feedstock.py", line 2250, in get_cfp_file_path
    pkg = get_most_recent_version("conda-forge-pinning")
  File "/opt/conda/lib/python3.10/site-packages/conda_smithy/configure_feedstock.py", line 2187, in get_most_recent_version
    request.raise_for_status()
  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.anaconda.org/package/conda-forge/conda-forge-pinning
INFO:webservices_dispatch_action.rerendering:token can change workflows: False
INFO:webservices_dispatch_action.rerendering:pushing and commenting: branch|owner|repo = rerender2|ericpre|numexpr-feedstock
Traceback (most recent call last):
  File "/opt/conda/bin/run-webservices-dispatch-action", line 33, in <module>
    sys.exit(load_entry_point('webservices-dispatch-action', 'console_scripts', 'run-webservices-dispatch-action')())
  File "/webservices_dispatch_action/webservices_dispatch_action/__main__.py", line 86, in main
    raise RuntimeError(
RuntimeError: Rerendering failed! error in push|rerender: False|True
```

**Comment by ericpre** [comment]
@conda-forge-admin , please re-render

**Comment by ericpre** [comment]
@ocefpaf, @xhochy, this should be good to go, thanks!

**Comment by xhochy** [comment]
@ericpre I'm not a maintainer here so I would only merge if nobody of the maintainers have reacted after a week.

**Comment by ericpre** [comment]
Thank you for following up, yes it makes sense!
I tagged you because from https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5289 you will be aware of what it is about! :)

**Pull request merged**
