### PR TITLE
numexpr v2.8.4

### PR DESCRIPTION
**Pull request by apmorton**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by apmorton** [comment]
Is there a way to pin those for just the windows builds?
The Linux and osx builds don't need this workaround.

I mentioned this in another PR, but ideally we could merge this to unblock
upstream packages. And then eventually resolve the issue in libblas and
rerender to remove the pin.

**Comment by ocefpaf** [comment]
> Is there a way to pin those for just the windows builds?

```yaml
mkl:  # [win]
  - 2022.1.0  # [win]
mkl_devel:  # [win]
  - 2022.1.0  # [win]
```

This should work (untested)!

**Comment by apmorton** [comment]
Appears to have worked perfectly, thanks!

**Comment by apmorton** [comment]
@ocefpaf any ideas? the build seems stuck in a loop trying to upload:
```

ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
copy results:
{}
Failed to upload due to copy from staging to production channel failed. Trying again in 10 seconds
```

**Comment by ocefpaf** [comment]
Not sure. Let's wait for the re-tries.

**Comment by apmorton** [comment]
They have all failed 😞

**Comment by apmorton** [comment]
Looking at a few other feedstock pipelines it appears this is not an issue with this feedstock, other main branch builds have failed to upload with the same error.

See: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=683522&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

**Comment by apmorton** [comment]
See: https://github.com/conda-forge/status/issues/143

**Pull request merged**
