### PR TITLE
Try again to upgrade to numexpr=2.8.4

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by apmorton** [comment]
@erykoff any idea whats broken here? this package is blocking https://github.com/conda-forge/pytables-feedstock/pull/82, which contains a bugfix that I'm currently blocked on - anything I can do to help get this published?

**Comment by erykoff** [comment]
@conda-forge-admin , please rerender

**Comment by erykoff** [comment]
I'm sorry, I have no idea.  I can't find any other uses of windows and mkl in this way, so I have no idea how it's even supposed to work, but the couple things that I've tried are clearly incorrect.  I see that @ericpre added the windows support originally...

**Comment by apmorton** [comment]
So! it looks like the `libblas` packages for windows specifically pin mkl 2022.1.0 where the linux/osx ones have `>=`.

I have a working build by manually pinning to 2022.1.0 in the windows `.ci_support` files over in https://github.com/conda-forge/numexpr-feedstock/pull/45

No idea if that is "correct", but I don't think it makes the world a worse place, and will unblock the pytables update.

**Pull request closed without merging**
